export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";

export const FETCH_DICTIONARY = "DICTIONARY/FETCH";
export const SET_QUERY = "DICTIONARY/SET_QUERY";
